apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: preprod-cloudcortex-hpa
  namespace: preprod
  labels:
    env: preprod
    app: cloudcortex
    layer: frontend
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: preprod-cloudcortex-deployment
  targetCPUUtilizationPercentage: 80